const defaults = {
  'activityBar.background': '#222',
  'activityBar.activeBackground': '#444',
  'activityBarBadge.foreground': '#222',
  'titleBar.activeBackground': '#222',
  'titleBar.inactiveForeground': '#222',
  'statusBar.foreground': '#222'
};

export default {
  turquiose: {
    ...defaults,
    'activityBar.activeBorder': '#45B8AC',
    'activityBar.foreground': '#45B8AC',
    'activityBar.inactiveForeground': '#45B8AC',
    'activityBarBadge.background': '#45B8AC',
    'titleBar.inactiveBackground': '#45B8AC',
    'titleBar.activeForeground': '#45B8AC',
    'statusBar.background': '#45B8AC',
    'statusBarItem.hoverBackground': '#45B8AC',
  },
  coral: {
    ...defaults,
    'activityBar.activeBorder': '#FF6F61',
    'activityBar.foreground': '#FF6F61',
    'activityBar.inactiveForeground': '#FF6F61',
    'activityBarBadge.background': '#FF6F61',
    'titleBar.inactiveBackground': '#FF6F61',
    'titleBar.activeForeground': '#FF6F61',
    'statusBar.background': '#FF6F61',
    'statusBarItem.hoverBackground': '#FF6F61',
  },
  rose: {
    ...defaults,
    'activityBar.activeBorder': '#F7CAC9',
    'activityBar.foreground': '#F7CAC9',
    'activityBar.inactiveForeground': '#F7CAC9',
    'activityBarBadge.background': '#F7CAC9',
    'titleBar.inactiveBackground': '#F7CAC9',
    'titleBar.activeForeground': '#F7CAC9',
    'statusBar.background': '#F7CAC9',
    'statusBarItem.hoverBackground': '#F7CAC9',
  },
  sand: {
    ...defaults,
    'activityBar.activeBorder': '#DFCFBE',
    'activityBar.foreground': '#DFCFBE',
    'activityBar.inactiveForeground': '#DFCFBE',
    'activityBarBadge.background': '#DFCFBE',
    'titleBar.inactiveBackground': '#DFCFBE',
    'titleBar.activeForeground': '#DFCFBE',
    'statusBar.background': '#DFCFBE',
    'statusBarItem.hoverBackground': '#DFCFBE',
  },
  violet: {
    ...defaults,
    'activityBar.activeBorder': '#6B5B95',
    'activityBar.foreground': '#6B5B95',
    'activityBar.inactiveForeground': '#6B5B95',
    'activityBarBadge.background': '#6B5B95',
    'titleBar.inactiveBackground': '#6B5B95',
    'titleBar.activeForeground': '#6B5B95',
    'statusBar.background': '#6B5B95',
    'statusBarItem.hoverBackground': '#6B5B95',
  },
};
